name: on-issue-created

on:
  issues:
    types: opened

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GH_REPO: ${{ github.repository }}
  NUMBER: ${{ github.event.issue.number }}
  BODY: ${{ github.event.issue.body }}

jobs:
  label-chromium:
    runs-on: ubuntu-latest
    if: "contains(env.BODY, 'browser: Chrome') || contains(env.BODY, 'browser: Edge')"
    permissions: write
    steps:
      - run: gh issue edit "$NUMBER" --add-label "Chromium"
  label-firefox:
    runs-on: ubuntu-latest
    if: "contains(env.BODY, 'browser: Firefox')"
    permissions: write
    steps:
      - run: gh issue edit "$NUMBER" --add-label "Firefox"
  label-safari:
    runs-on: ubuntu-latest
    if: "contains(env.BODY, 'browser: Safari')"
    permissions: write
    steps:
      - run: gh issue edit "$NUMBER" --add-label "Safari"
