name: on-issue-created

on:
  issues:
    types: opened

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GH_REPO: ${{ github.repository }}
  NUMBER: ${{ github.event.issue.number }}

jobs:
  label-chromium:
    runs-on: ubuntu-latest
    if: "contains(github.event.issue.body, 'browser: Chrome')"
    permissions:
      issues: write
    steps:
      - run: gh issue edit "$NUMBER" --add-label "Chromium"
  label-edge:
    runs-on: ubuntu-latest
    if: "contains(github.event.issue.body, 'browser: Edge')"
    permissions:
      issues: write
    steps:
      - run: gh issue edit "$NUMBER" --add-label "Edge"
  label-firefox:
    runs-on: ubuntu-latest
    if: "contains(github.event.issue.body, 'browser: Firefox')"
    permissions:
      issues: write
    steps:
      - run: gh issue edit "$NUMBER" --add-label "Firefox"
  label-safari:
    runs-on: ubuntu-latest
    if: "contains(github.event.issue.body, 'browser: Safari')"
    permissions:
      issues: write
    steps:
      - run: gh issue edit "$NUMBER" --add-label "Safari"
  label-ubol:
    runs-on: ubuntu-latest
    if: "contains(github.event.issue.body, 'name: uBlock Origin Lite')"
    permissions:
      issues: write
    steps:
      - run: gh issue edit "$NUMBER" --add-label "uBOL"
